import "../../index.css";

const icons = [
  'alert',
  'android',
  'apple',
  'arrow-down',
  'arrow-down-deprecated',
  'arrow-left',
  'arrow-right',
  'arrow-up',
  'arrow-up-deprecated',
  'ban',
  'basketball',
  'bell',
  'betslip',
  'boosted-odds',
  'boosted-odds-circle',
  'calculator',
  'calendar',
  'card',
  'caret',
  'cashout',
  'check',
  'close-x',
  'copy',
  'cross',
  'cross-circled-fill',
  'cross-squared',
  'cut-plus',
  'cut-plus-small',
  'delete-deprecated',
  'deposit',
  'direct-link-squared-black',
  'ed-winners',
  'exclamation',
  'facebook-circled',
  'facebook-squared-black',
  'fb',
  'football',
  'games',
  'gift',
  'hamburger-inclined',
  'headphones',
  'help',
  'help-2',
  'help-menu',
  'home',
  'hot',
  'icon-boosted',
  'information',
  'instagram-circled',
  'items',
  'jackpot',
  'join-now',
  'live-now',
  'live-timer',
  'loader',
  'loader-deprecated',
  'locked',
  'log-in',
  'log-out',
  'logo-bp',
  'marketing-message',
  'megaphone',
  'menu-deprecated',
  'menu-sports',
  'message-betslip-issue',
  'message-big-win',
  'message-compensation',
  'message-critical-update',
  'message-customer-support',
  'message-general',
  'message-operational',
  'message-regular-win',
  'messages',
  'multiple',
  'my-bets',
  'my-bets-2',
  'my-bets-3',
  'my-bets-warning',
  'notification',
  'operational-message',
  'pawa-pot',
  'pawa6',
  'pawaboost',
  'pencil',
  'plus',
  'popular',
  'recent',
  'reload',
  'responsible-gaming',
  'rules',
  'search',
  'share',
  'signal-delayed',
  'signal-unavailable',
  'single',
  'sort',
  'sports',
  'stadium',
  'star',
  'star-active',
  'statement',
  'statistics',
  'telegram',
  'tennis',
  'tennis-deprecated',
  'top-menu',
  'tournament',
  'tournament-big-win',
  'two-up',
  'unlocked',
  'upcoming',
  'virtual',
  'whatsapp',
  'whatsapp-squared-black',
  'withdraw',
  'x-circled',
  'x-squared-black',
];

export default {
  title: 'Icons/All',
};

export const AllIcons = () => (
  <div style={{ display: 'flex', flexWrap: 'wrap', gap: '20px' }}>
    {icons.map((name) => (
      <div key={name} style={{ width: 100, textAlign: 'center' }}>
        <i className={`fak fa-${name}`} style={{ fontSize: 24 }}></i>
        <div style={{ marginTop: 8, fontSize: 12 }}>{name}</div>
      </div>
    ))}
  </div>
);
